Protect `spring-cherry-pick` against pushing commit to itself
The `Auto-cherry-pick` commit may be pushed into a branch
for which the cherry-pick is supposed to happen.
So, check in loop for `$branches` if requested branch is not exactly same where the commit has been just pushed.

* Fix typos and some sentence in the `README.md` according to the current state of things.

diff --git a/.github/workflows/spring-cherry-pick.yml b/.github/workflows/spring-cherry-pick.yml
--- a/.github/workflows/spring-cherry-pick.yml
+++ b/.github/workflows/spring-cherry-pick.yml
@@ -39,15 +39,18 @@ jobs:
           branches=$(echo "$COMMIT_MESSAGE" | grep "$CHERRY_PICK_TOKEN" | grep -o1 -E "([0-9]+\.[0-9]+\.x)")
           for branch in $branches
           do 
-            git checkout "$branch"
-            if git cherry-pick ${{ github.sha }} -x
+            if [ "$branch" != '${{ github.ref_name }}' ]
             then
-              echo "::notice title=Commit cherry-picked::${{ github.sha }} to branch $branch"
-            else
-              echo "::error title=Cannot cherry-pick::${{ github.sha }} to branch $branch. Manual procedure required"
-              exit 1
+              git checkout "$branch"
+              if git cherry-pick ${{ github.sha }} -x
+              then
+                echo "::notice title=Commit cherry-picked::${{ github.sha }} to branch $branch"
+              else
+                echo "::error title=Cannot cherry-pick::${{ github.sha }} to branch $branch. Manual procedure required"
+                exit 1
+              fi
+              branchCommitMessage=$(git log -1 --pretty=%B | grep -v "$CHERRY_PICK_TOKEN")
+              git commit --amend -o -m "$branchCommitMessage"  
+              git push origin $branch    
             fi
-            branchCommitMessage=$(git log -1 --pretty=%B | grep -v "$CHERRY_PICK_TOKEN")
-            git commit --amend -o -m "$branchCommitMessage"  
-            git push origin $branch
           done
